services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pathfind-app
    ports:
      - "3000:3000"
    volumes:
      - data:/app/data
    env_file:
      - .env
    restart: always

volumes:
  data:
